#include <iostream>
#include <new>

using std::endl;

const int capitalDiff = 'A' - 'a'; // The difference between capital and lowercase letters
const int MAX_STRING = 1000;       // Max length of a string
const int MAX_KEYWORD = 10;        // Max length of each encryption keyword

/*
--------------------- 02 Cryptography ---------------------
Create a program which can encrypt a string by replacing
each letter in it with a string(len <= 10) according to a
table, generated by the user. Let the program not
differentiate lower- and uppercase letters.

The program first takes as input an integer - K - followed
by K pairs of a character and a string, separated by a
space. Each pair should be on a new line. This represents
the table, according to which, each string will be
encrypted.

Then, read an integer N, followed by N strings, which are
to be encrypted using the algorithm, as well as an integer
M, followed by M strings to be decrypted.

The encrypted and decrypted strings should be stored
dynamically.

------------------------ EXAMPLE: -------------------------
input:  8
        i ala
        l bala
        d cana
        e h
        t disco
        o electro
        c pro
        a some
        
        1
        I l0ve to code!
        
        1
        ala somem discoelectroelectro proelectroelectrobala!

output: ala bala0vh discoelectro proelectrocanah!
        i am too cool!
-----------------------------------------------------------
*/

bool letterIs (const char ch, const char letter)
{
    if (ch == letter || ch == (letter + capitalDiff))
        return true;

    return false;
}

int main ()
{
    return 0;
}